version: '3.8'
services:
  js:
    container_name: js
    build:
      context: .
      dockerfile: ./.docker/js/Dockerfile
    volumes:
      - './:/var/www/html/js'
      - '/var/www/html/js/node_modules'
    working_dir: '/var/www/html/js'
    ports:
      - '3000:3000'
    command: ['pnpm', 'dev']
    networks:
      - network

  go:
    container_name: go
    build:
      context: .
      dockerfile: ./.docker/go/Dockerfile
    volumes:
      - './:/app'
    ports:
      - '8080:8080'
    environment:
      - ORIGIN_URL=${ORIGIN_URL}
      - EMAIL_TO=${EMAIL_TO}
      - EMAIL_FROM=${EMAIL_FROM}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - BASE_TITLE=${BASE_TITLE}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    networks:
      - network

networks:
  network:
    driver: bridge
