name: Deploy Containers to ECR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build and push PushNotification Docker image
        run: |
          docker build -t ${{ secrets.FUNCTIONS_PUSHNOTIFICATION }} --platform linux/x86_64 functions/PushNotification/
          docker tag ${{ secrets.FUNCTIONS_PUSHNOTIFICATION }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.FUNCTIONS_PUSHNOTIFICATION }}:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.FUNCTIONS_PUSHNOTIFICATION }}:latest

      - name: Build and push Recaptcha Docker image
        run: |
          docker build -t ${{ secrets.FUNCTIONS_RECAPTCHA }} --platform linux/x86_64 functions/Recaptcha/
          docker tag ${{ secrets.FUNCTIONS_RECAPTCHA }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.FUNCTIONS_RECAPTCHA }}:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.FUNCTIONS_RECAPTCHA }}:latest

      - name: Build and push SendEmail Docker image
        run: |
          docker build -t ${{ secrets.FUNCTIONS_EMAIL }} --platform linux/x86_64 functions/SendEmail/
          docker tag ${{ secrets.FUNCTIONS_EMAIL }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.FUNCTIONS_EMAIL }}:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.FUNCTIONS_EMAIL }}:latest
