name: Update Lambda with Latest ECR Image

on:
  workflow_run:
    workflows: ['Deploy Containers to ECR']
    types:
      - completed

jobs:
  update-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Update PushNotification Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.FUNCTIONS_PUSHNOTIFICATION }} \
            --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.FUNCTIONS_PUSHNOTIFICATION }}:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Update Recaptcha Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.FUNCTIONS_RECAPTCHA }} \
            --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.FUNCTIONS_RECAPTCHA }}:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Update SendEmail Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.FUNCTIONS_EMAIL }} \
            --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.FUNCTIONS_EMAIL }}:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
