name: Deploy XML to S3

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Set environment variables
        run: |
          echo "MICROCMS_SERVICE_DOMAIN=${{ secrets.MICROCMS_SERVICE_DOMAIN }}" >> $GITHUB_ENV
          echo "MICROCMS_API_KEY=${{ secrets.MICROCMS_API_KEY }}" >> $GITHUB_ENV

      - name: Generate XML files
        run: npm run generate

      - name: Install AWS CLI
        run: sudo apt-get install awscli -y

      - name: Upload XML files to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ./public/sitemap-0.xml s3://${{ secrets.S3_BUCKET_NAME }}/sitemap-0.xml --region ${{ secrets.AWS_REGION }} --debug
          aws s3 cp ./public/rss.xml s3://${{ secrets.S3_BUCKET_NAME }}/rss.xml --region ${{ secrets.AWS_REGION }} --debug

      - name: Invalidate CloudFront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
